name: Security scan
description: Common Github Action for source code security scanning

inputs:
  token:
    description: GitHub Token
    required: true
    default: ''
  severity:
    description: List of severities
    required: true
    default: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'

runs:
  using: composite
  steps:
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: false
        format: 'table'
        output: trivy-scan-results.output
        severity: ${{ inputs.severity }}
        exit-code: 0

    - name: Read Trivy results
      id: trivy-get-results
      shell: bash -e {0}
      run: |
          echo "trivy-scan-result=$(jq ".Results[].Vulnerabilities" trivy-scan-results.output)" >> $GITHUB_OUTPUT

    - name: Store Trivy scan results in env
      shell: bash -e {0}
      run: |
          echo 'TRIVY_FS_RESULTS<<EOF' >> $GITHUB_ENV
          cat trivy-scan-results.output >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

    - name: Comment Trivy scan results in PR
      uses: thollander/actions-comment-pull-request@v1
      if: steps.trivy-get-results.outputs.trivy-scan-result != '[]'
      with:
        message: |
          ## Trivy results:
          ### Source code scaning results
          ```
          ${{ env.TRIVY_FS_RESULTS }}
          ```
        GITHUB_TOKEN: ${{ inputs.token }}
